added main,book,terms pages
ClevertecFrontendLab/sprint1-pollsav pull request #1
Opened 2023-02-01 19:48 UTC by pollsav

2023-02-01 19:51 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675281084/content-window.png)

2023-02-01 19:56 UTC, Gaurrus requested changes

2023-02-01 19:56 UTC, Gaurrus commented on package.json
>      "stylelint-prettier": "^2.0.0"
![image](https://user-images.githubusercontent.com/85307211/216149037-03616522-b88b-482e-ad0d-8f787df0e11a.png)
в макете для 320 ширины текст не так расположен, и сероватый фон должен быть на всю ширину экрана

2023-02-01 20:01 UTC, pollsav commented on package.json
>      "stylelint-prettier": "^2.0.0"
Знаю, может можно на 2 спринте исправить? Не успеваю сегодня уже

2023-02-01 20:05 UTC, Gaurrus requested changes

2023-02-01 20:05 UTC, Gaurrus commented on src/ui/components/nav-list/buttons/buttons.jsx
> +      {direction === 'row' ? <Rowbutton fill='#FFFFFF' /> : <Rowbutton fill='#A7A7A7' />}
цвет в css никак не вынести?)

2023-02-01 20:05 UTC, Gaurrus commented on package.json
>      "stylelint-prettier": "^2.0.0"
ну помимо этого еще есть косяки по коду

2023-02-01 20:05 UTC, Gaurrus commented on src/ui/components/rating/rating.jsx
> +    <Star />
map

2023-02-01 20:07 UTC, Gaurrus commented on src/ui/components/rating/rating.jsx
> +    <Star />
исправить к следующему спринту

2023-02-01 20:07 UTC, Gaurrus commented on src/ui/components/nav-list/buttons/buttons.jsx
> +      {direction === 'row' ? <Rowbutton fill='#FFFFFF' /> : <Rowbutton fill='#A7A7A7' />}
исправить сейчас

2023-02-01 20:07 UTC, Gaurrus commented on src/pages/main/main-page.jsx
> +          </Link>
исправить к следующему спринту

2023-02-01 20:08 UTC, Gaurrus commented on package.json
>      "stylelint-prettier": "^2.0.0"
на соответствие макету надо исправлять

2023-02-02 08:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/pollsav/1675325012/content-window.png)

2023-02-02 08:11 UTC, Gaurrus approved these changes

2023-02-02 08:14 UTC, merged